server:
  port: 8001
  servlet:
    context-path: /graphql-demo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1405
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        #ddl-auto: create-drop
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 35
          order_inserts: true
          order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
        query:
          fail_on_pagination_over_collection_fetch: true
      jakarta:
        persistence:
          sharedCache:
            mode: NONE
  graphql:
    path: /tariff-package-graphql
    graphiql:
      enabled: true

application:
  client:
    pokemon-berry:
      url: https://pokeapi.co/api

blaze:
  query:
    search:
      restrictions:
        id: eq
        packageType: like
        commission: eq